services:
  mysql:
    image: mysql:8.4
    container_name: analytics_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: commerce_db
      TZ: Asia/Kolkata
    ports:
      - "127.0.0.1:3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot_pw"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_data:
